server:
   port: 5008 
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always  
 
    
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: batch-center
  batch:
    job:
      enabled: false
  shardingsphere:
    sharding:
      default-data-source-name: ds0
      default-key-generator:
        column: id
        props:
          worker:
            id: ${workerId}
        type: SNOWFLAKE
    datasource:
      names: ds0
      ds0:
        connectionTimeoutMilliseconds: 30000
        idleTimeoutMilliseconds: 60000
        maintenanceIntervalMilliseconds: 30000
        maxLifetimeMilliseconds: 1800000
        maxPoolSize: 50
        minPoolSize: 50
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: com.zaxxer.hikari.HikariDataSource
        username: root
        password: root
        jdbc-url: jdbc:mysql://59.110.164.254:3306/batch-center?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false 
    
       
mybatis-plus:     
  global-config:
    banner: false   
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl 
  mapper-locations: classpath*:com/open/**/dao/*.xml  
 

logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
#    com.neusoft: DEBUG     
#    com.netflix: DEBUG                    #用于心跳检测输出的日志    


  
 